site_name: Islam Portfolio
site_author: Islam Mohammed Salama
site_description: Islam Mohammed Salama Portfolio .
copyright: Copyright &copy; 2024 Islam Mohamed
repo_url: https://github.com/IslamMohammedSalama/IslamMohammedSalama.github.io.git
theme:
  logo: /assets/images/islam.png
  favicon: /assets/images/ic_launcher.png
  name: material
  features:
    - content.code.copy
    - content.code.highlight
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - navigation.footer
  theme:
  palette:

    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - search
  - tags