site_name: Islam Portfolio
site_author: Islam Mohammed Salama
site_description: Islam Mohammed Salama Portfolio .
copyright: Copyright &copy; 2024 Islam Mohamed
repo_url: https://github.com/IslamMohammedSalama/IslamMohammedSalama.github.io.git

# extra_css:
#   - stylesheets/extra.css

theme:
  # custom_dir: overrides
  name: material
  logo: /assets/images/islam.png
  favicon: /assets/images/islam.png

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    # - toc.integrate
